### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by NicholasProdehl** [NicholasProdehl/driving-game#1]
# Feature

User can see their car.

## Workflow

Be sure to stick with [the workflow](https://github.com/Learning-Fuze/driving-game-instructions#workflow) while building.

## Issue Template

Open a new Issue on your GitHub repository with the title **User can see their car** and paste the following block of [Markdown](https://guides.github.com/features/mastering-markdown/) into the comment box.

You will attempt to write your own task list before coding this feature. Refer to past projects for an example of what a task list should look like. **Lots of small tasks is better than a few large tasks.**

```md
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [ ] ...
- [ ] Setup HTML for background + image
- [ ] Make background color green
- [ ] Put image of racecar on top left of screen facing right.`

```

## Example

This is just an example in case you need it.

![user can see their car](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/demos/driving-game/user-can-see-their-car.png)
